//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class LEVEL
{

    private LEVELROZMERY rOZMERYField;

    private LEVELSPAWN sPAWNField;

    private LEVELOBJEKTY oBJEKTYField;

    /// <remarks/>
    public LEVELROZMERY ROZMERY
    {
        get
        {
            return this.rOZMERYField;
        }
        set
        {
            this.rOZMERYField = value;
        }
    }

    /// <remarks/>
    public LEVELSPAWN SPAWN
    {
        get
        {
            return this.sPAWNField;
        }
        set
        {
            this.sPAWNField = value;
        }
    }

    /// <remarks/>
    public LEVELOBJEKTY OBJEKTY
    {
        get
        {
            return this.oBJEKTYField;
        }
        set
        {
            this.oBJEKTYField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELROZMERY
{

    private int sIRKAField;

    private int vYSKAField;

    /// <remarks/>
    public int SIRKA
    {
        get
        {
            return this.sIRKAField;
        }
        set
        {
            this.sIRKAField = value;
        }
    }

    /// <remarks/>
    public int VYSKA
    {
        get
        {
            return this.vYSKAField;
        }
        set
        {
            this.vYSKAField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELSPAWN
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTY
{

    private LEVELOBJEKTYBALVAN[] bALVANField;

    private LEVELOBJEKTYREBRIK[] rEBRIKField;

    private LEVELOBJEKTYSTENA[] sTENAField;

    private LEVELOBJEKTYVYCHOD[] vYCHODField;

    private LEVELOBJEKTYPICHLIACE[] pICHLIACEField;

    private LEVELOBJEKTYPREPINAC[] pREPINACField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BALVAN")]
    public LEVELOBJEKTYBALVAN[] BALVAN
    {
        get
        {
            return this.bALVANField;
        }
        set
        {
            this.bALVANField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("REBRIK")]
    public LEVELOBJEKTYREBRIK[] REBRIK
    {
        get
        {
            return this.rEBRIKField;
        }
        set
        {
            this.rEBRIKField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("STENA")]
    public LEVELOBJEKTYSTENA[] STENA
    {
        get
        {
            return this.sTENAField;
        }
        set
        {
            this.sTENAField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("VYCHOD")]
    public LEVELOBJEKTYVYCHOD[] VYCHOD
    {
        get
        {
            return this.vYCHODField;
        }
        set
        {
            this.vYCHODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PICHLIACE")]
    public LEVELOBJEKTYPICHLIACE[] PICHLIACE
    {
        get
        {
            return this.pICHLIACEField;
        }
        set
        {
            this.pICHLIACEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PREPINAC")]
    public LEVELOBJEKTYPREPINAC[] PREPINAC
    {
        get
        {
            return this.pREPINACField;
        }
        set
        {
            this.pREPINACField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYBALVAN
{

    private LEVELOBJEKTYBALVANSURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYBALVANSURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYBALVANSURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYREBRIK
{

    private LEVELOBJEKTYREBRIKSURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYREBRIKSURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYREBRIKSURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYSTENA
{

    private LEVELOBJEKTYSTENASURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYSTENASURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYSTENASURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYVYCHOD
{

    private LEVELOBJEKTYVYCHODSURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYVYCHODSURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYVYCHODSURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYPICHLIACE
{

    private LEVELOBJEKTYPICHLIACESURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYPICHLIACESURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYPICHLIACESURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYPREPINAC
{

    private LEVELOBJEKTYPREPINACSURADNICE sURADNICEField;

    private bool sOLIDField;

    private int wEIGHTField;

    /// <remarks/>
    public LEVELOBJEKTYPREPINACSURADNICE SURADNICE
    {
        get
        {
            return this.sURADNICEField;
        }
        set
        {
            this.sURADNICEField = value;
        }
    }

    /// <remarks/>
    public bool SOLID
    {
        get
        {
            return this.sOLIDField;
        }
        set
        {
            this.sOLIDField = value;
        }
    }

    /// <remarks/>
    public int WEIGHT
    {
        get
        {
            return this.wEIGHTField;
        }
        set
        {
            this.wEIGHTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class LEVELOBJEKTYPREPINACSURADNICE
{

    private int xField;

    private int yField;

    /// <remarks/>
    public int X
    {
        get
        {
            return this.xField;
        }
        set
        {
            this.xField = value;
        }
    }

    /// <remarks/>
    public int Y
    {
        get
        {
            return this.yField;
        }
        set
        {
            this.yField = value;
        }
    }
}
