//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quadrax.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quadrax.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Bg {
            get {
                object obj = ResourceManager.GetObject("Bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg1 {
            get {
                object obj = ResourceManager.GetObject("bg1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boulder_01 {
            get {
                object obj = ResourceManager.GetObject("boulder_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ladder {
            get {
                object obj = ResourceManager.GetObject("ladder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LEVEL&gt;
        ///	&lt;ROZMERY&gt;
        ///		&lt;SIRKA&gt;10&lt;/SIRKA&gt;
        ///		&lt;VYSKA&gt;10&lt;/VYSKA&gt;
        ///	&lt;/ROZMERY&gt;
        ///	&lt;SPAWN&gt;
        ///		&lt;X1&gt;40&lt;/X1&gt;
        ///		&lt;Y1&gt;430&lt;/Y1&gt;
        ///    &lt;X2&gt;60&lt;/X2&gt;
        ///    &lt;Y2&gt;430&lt;/Y2&gt;
        ///	&lt;/SPAWN&gt;
        ///	&lt;OBJEKTY&gt;
        ///    &lt;BALVAN&gt;
        ///      &lt;SURADNICE&gt;
        ///        &lt;X&gt;250&lt;/X&gt;
        ///        &lt;Y&gt;445&lt;/Y&gt;
        ///      &lt;/SURADNICE&gt;
        ///      &lt;SOLID&gt;true&lt;/SOLID&gt;
        ///      &lt;WEIGHT&gt;15&lt;/WEIGHT&gt;
        ///    &lt;/BALVAN&gt;
        ///		&lt;REBRIK&gt;
        ///			&lt;SURADNICE&gt;
        ///				&lt;X&gt;200&lt;/X&gt;
        ///				&lt;Y&gt;150&lt;/Y&gt;
        ///			&lt;/SURADNICE&gt;
        ///      &lt;VELKOST&gt;
        ///        &lt;VYSKA&gt;10&lt;/VYSKA&gt;
        ///      &lt;/VELKOST&gt;
        ///			&lt;SOLID&gt;true&lt;/SOLID&gt;
        ///			&lt;WEIGHT&gt;6 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level {
            get {
                return ResourceManager.GetString("level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LEVEL&gt;
        ///	&lt;ROZMERY&gt;
        ///		&lt;SIRKA&gt;500&lt;/SIRKA&gt;
        ///		&lt;VYSKA&gt;225&lt;/VYSKA&gt;
        ///	&lt;/ROZMERY&gt;
        ///	&lt;SPAWN&gt;
        ///		&lt;X1&gt;75&lt;/X1&gt;
        ///		&lt;Y1&gt;400&lt;/Y1&gt;
        ///		&lt;X2&gt;150&lt;/X2&gt;
        ///		&lt;Y2&gt;400&lt;/Y2&gt;
        ///	&lt;/SPAWN&gt;
        ///	&lt;OBJEKTY&gt;
        ///		&lt;BALVAN&gt;
        ///		  &lt;SURADNICE&gt;
        ///			&lt;X&gt;450&lt;/X&gt;
        ///			&lt;Y&gt;125&lt;/Y&gt;
        ///		  &lt;/SURADNICE&gt;
        ///		  &lt;SOLID&gt;true&lt;/SOLID&gt;
        ///		  &lt;WEIGHT&gt;50&lt;/WEIGHT&gt;
        ///		&lt;/BALVAN&gt;
        ///		&lt;REBRIK&gt;
        ///			&lt;SURADNICE&gt;
        ///				&lt;X&gt;280&lt;/X&gt;
        ///				&lt;Y&gt;50&lt;/Y&gt;
        ///			&lt;/SURADNICE&gt;
        ///			&lt;VELKOST&gt;
        ///				&lt;VYSKA&gt;16&lt;/VYSKA&gt;
        ///			&lt;/VELKOST&gt;
        ///			&lt;SOLID&gt;false&lt;/SOLID&gt;
        ///			&lt;WEIGHT&gt;60&lt;/WEIGHT&gt;
        ///			&lt;/REBRIK&gt;
        ///		&lt;STEN [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level1 {
            get {
                return ResourceManager.GetString("level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LEVEL&gt;
        ///  &lt;ROZMERY&gt;
        ///    &lt;SIRKA&gt;500&lt;/SIRKA&gt;
        ///    &lt;VYSKA&gt;225&lt;/VYSKA&gt;
        ///  &lt;/ROZMERY&gt;
        ///  &lt;SPAWN&gt;
        ///    &lt;X1&gt;330&lt;/X1&gt;
        ///    &lt;Y1&gt;50&lt;/Y1&gt;
        ///    &lt;X2&gt;150&lt;/X2&gt;
        ///    &lt;Y2&gt;400&lt;/Y2&gt;
        ///  &lt;/SPAWN&gt;
        ///  &lt;OBJEKTY&gt;
        ///    &lt;BALVAN&gt;
        ///      &lt;SURADNICE&gt;
        ///        &lt;X&gt;450&lt;/X&gt;
        ///        &lt;Y&gt;125&lt;/Y&gt;
        ///      &lt;/SURADNICE&gt;
        ///      &lt;SOLID&gt;true&lt;/SOLID&gt;
        ///      &lt;WEIGHT&gt;50&lt;/WEIGHT&gt;
        ///    &lt;/BALVAN&gt;
        ///    &lt;REBRIK&gt;
        ///      &lt;SURADNICE&gt;
        ///        &lt;X&gt;290&lt;/X&gt;
        ///        &lt;Y&gt;50&lt;/Y&gt;
        ///      &lt;/SURADNICE&gt;
        ///      &lt;VELKOST&gt;
        ///        &lt;VYSKA&gt;17&lt;/VYSKA&gt;
        ///      &lt;/VELKOST&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string level2 {
            get {
                return ResourceManager.GetString("level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lever_1 {
            get {
                object obj = ResourceManager.GetObject("Lever_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Lever_2 {
            get {
                object obj = ResourceManager.GetObject("Lever_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P1CL1 {
            get {
                object obj = ResourceManager.GetObject("P1CL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P1CL2 {
            get {
                object obj = ResourceManager.GetObject("P1CL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P1CL3 {
            get {
                object obj = ResourceManager.GetObject("P1CL3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2CL1 {
            get {
                object obj = ResourceManager.GetObject("P2CL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2CL2 {
            get {
                object obj = ResourceManager.GetObject("P2CL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap P2CL3 {
            get {
                object obj = ResourceManager.GetObject("P2CL3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2L1 {
            get {
                object obj = ResourceManager.GetObject("Player2L1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2L2 {
            get {
                object obj = ResourceManager.GetObject("Player2L2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2L3 {
            get {
                object obj = ResourceManager.GetObject("Player2L3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2L4 {
            get {
                object obj = ResourceManager.GetObject("Player2L4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2R1 {
            get {
                object obj = ResourceManager.GetObject("Player2R1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2R2 {
            get {
                object obj = ResourceManager.GetObject("Player2R2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2R3 {
            get {
                object obj = ResourceManager.GetObject("Player2R3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Player2R4 {
            get {
                object obj = ResourceManager.GetObject("Player2R4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerL1 {
            get {
                object obj = ResourceManager.GetObject("PlayerL1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerL2 {
            get {
                object obj = ResourceManager.GetObject("PlayerL2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerL3 {
            get {
                object obj = ResourceManager.GetObject("PlayerL3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerL4 {
            get {
                object obj = ResourceManager.GetObject("PlayerL4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerR1 {
            get {
                object obj = ResourceManager.GetObject("PlayerR1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerR2 {
            get {
                object obj = ResourceManager.GetObject("PlayerR2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerR3 {
            get {
                object obj = ResourceManager.GetObject("PlayerR3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PlayerR4 {
            get {
                object obj = ResourceManager.GetObject("PlayerR4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;LEVEL&gt;
        ///	&lt;ROZMERY&gt;
        ///		&lt;SIRKA&gt;500&lt;/SIRKA&gt;
        ///		&lt;VYSKA&gt;225&lt;/VYSKA&gt;
        ///	&lt;/ROZMERY&gt;
        ///	&lt;SPAWN&gt;
        ///		&lt;X1&gt;100&lt;/X1&gt;
        ///		&lt;Y1&gt;100&lt;/Y1&gt;
        ///		&lt;X2&gt;450&lt;/X2&gt;
        ///		&lt;Y2&gt;400&lt;/Y2&gt;
        ///	&lt;/SPAWN&gt;
        ///	&lt;OBJEKTY&gt;
        ///    &lt;BALVAN&gt;
        ///      &lt;SURADNICE&gt;
        ///        &lt;X&gt;350&lt;/X&gt;
        ///        &lt;Y&gt;450&lt;/Y&gt;
        ///      &lt;/SURADNICE&gt;
        ///      &lt;SOLID&gt;true&lt;/SOLID&gt;
        ///      &lt;WEIGHT&gt;50&lt;/WEIGHT&gt;
        ///    &lt;/BALVAN&gt;
        ///    &lt;REBRIK&gt;
        ///			&lt;SURADNICE&gt;
        ///				&lt;X&gt;280&lt;/X&gt;
        ///				&lt;Y&gt;50&lt;/Y&gt;
        ///			&lt;/SURADNICE&gt;
        ///			&lt;VELKOST&gt;
        ///				&lt;VYSKA&gt;16&lt;/VYSKA&gt;
        ///			&lt;/VELKOST&gt;
        ///			&lt;SOLID&gt;false&lt;/SOLID&gt;
        ///			&lt;WEIGHT&gt;60&lt;/WEIGH [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestLevel {
            get {
                return ResourceManager.GetString("TestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thorns {
            get {
                object obj = ResourceManager.GetObject("thorns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_01 {
            get {
                object obj = ResourceManager.GetObject("wall_01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_02 {
            get {
                object obj = ResourceManager.GetObject("wall_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_03 {
            get {
                object obj = ResourceManager.GetObject("wall_03", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_04 {
            get {
                object obj = ResourceManager.GetObject("wall_04", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wall_05 {
            get {
                object obj = ResourceManager.GetObject("wall_05", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
